services:
  frontend:
    build: D:\FACULTATE\AnulIV\SD
    ports:
      - "4200:4200"
    networks:
      - my_network

  users-service:
    build: D:\FACULTATE\AnulIV\SD
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      POSTGRES_HOST: user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresServer1
    depends_on:
      - user_db

  devices-service:
    build: D:\FACULTATE\AnulIV\SD
    ports:
      - "8081:8081"
    networks:
      - my_network
    environment:
      POSTGRES_HOST: device_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresServer1
    depends_on:
      - device_db

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my_network

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresServer1
      POSTGRES_DB: user_db
    volumes:
      - user_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  device_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresServer1
      POSTGRES_DB: device_db
    volumes:
      - device_db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network

volumes:
  user_db-data:
  device_db-data:

networks:
  my_network:
    driver: bridge
