services:
  traefik:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - my_network

  frontend:
    build: D:\FACULTATE\Anul_IV\SD\AngularFrontEnd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=4200"
    networks:
      - my_network

  users-service:
    build: D:\FACULTATE\Anul_IV\SD\UserMicroservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-service.rule=Host(`users.localhost`)"
      - "traefik.http.services.users-service.loadbalancer.server.port=8080"
    networks:
      - my_network
    environment:
      POSTGRES_HOST: user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresServer1
    depends_on:
      - user_db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  devices-service:
    build: D:\FACULTATE\Anul_IV\SD\DeviceMicroservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.devices-service.rule=Host(`devices.localhost`)"
      - "traefik.http.services.devices-service.loadbalancer.server.port=8081"
    networks:
      - my_network
    environment:
      POSTGRES_HOST: device_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresServer1
    depends_on:
      - device_db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  monitoring-service:
    build: D:\FACULTATE\Anul_IV\SD\Monitoring-CommunicationMicroservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-service.rule=Host(`monitoring.localhost`)"
      - "traefik.http.services.monitoring-service.loadbalancer.server.port=8082"
    networks:
      - my_network
    environment:
      POSTGRES_HOST: monitoring_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresServer1
    depends_on:
      - monitoring_db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  chat-service:
    build: D:\FACULTATE\Anul_IV\SD\ChatMicroservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-service.rule=Host(`chat.localhost`)"
      - "traefik.http.services.chat-service.loadbalancer.server.port=8084"
    networks:
      - my_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my_network

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresServer1
      POSTGRES_DB: user_db
    volumes:
      - user_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  device_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresServer1
      POSTGRES_DB: device_db
    volumes:
      - device_db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network

  monitoring_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresServer1
      POSTGRES_DB: monitoring_db
    volumes:
      - monitoring_db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - my_network

volumes:
  user_db-data:
  device_db-data:
  monitoring_db-data:

networks:
  my_network:
    driver: bridge
